alert("......success......");
var obj="this is a string object.";
alert(obj);
length=obj.length;
alert(length);
var index=obj.indexOf("is");
var index2=obj.indexOf("is", index + 1);
var index3=obj.indexOf("This");
// var index4=obj.lastIndexOf("is", index - 1);
alert(index);
alert(index2);
alert(index3);
// alert(index4);
